### ISSUE TITLE
Exported absolute_datetime value is not correct. 

### ISSUE THREAD

**Issue by jacob-kamminga** [jacob-kamminga/AI-Sensus#108]
It should be the same as the displayed time during annotating. This should probably be UTC time converted to project timezone.

The image below shows the labeling app, and a figure that was generated after exporting the data to csv and importing the csv to a Matlab script. 

![image](https://user-images.githubusercontent.com/10651664/172660292-d24c179b-477b-4c13-9360-81ab3b20169b.png)

**Comment by MaxLievense** [comment]
Need more details for this case.
- Did you set an offset? My test case correctly outputs the absolute time as the time of the reference video
- What timezones are the video and mcu set?
Maybe send this project in a zip so I can reuse it.

**Comment by MaxLievense** [comment]
Lead:
https://github.com/jacob-kamminga/AI-Sensus/blob/87e3532bdc4028556610d7955cd36716aec065ce/gui/dialogs/export_progress_dialog.py#L100-L101

**Comment by jacob-kamminga** [comment]
Changing:
https://github.com/jacob-kamminga/AI-Sensus/blob/87e3532bdc4028556610d7955cd36716aec065ce/gui/dialogs/export_progress_dialog.py#L100-L101
to 

`
if not sensor_data.add_abs_dt_col(use_utc=False): 
     continue
`


results in error:
![image](https://user-images.githubusercontent.com/10651664/176515853-2af77066-590c-409f-934b-cc2461d2ff3f.png)

**Comment by jacob-kamminga** [comment]
This is the project. The project uses the validation test set that is shared on the AI Sensus shared Google drive. [TEST.zip](https://github.com/jacob-kamminga/AI-Sensus/files/9013473/TEST.zip)
