### ISSUE TITLE
Error in Label Settings after label creation

### ISSUE THREAD

**Issue by MaxLievense** [jacob-kamminga/AI-Sensus#57]
![image](https://user-images.githubusercontent.com/49908115/141771129-0d3afe53-6856-4d60-be30-25bef105a3e7.png)

Case:
1. open Label Settings
2. Press "Add" in Add new label
3. Press "Save"
Error

**Comment by JRitmeester** [comment]
Related to #92

**Comment by MaxLievense** [comment]
No longer an error
